Nightly OS Boot: Cache prepared images (#142)
## Description

This commit caches the prepared images for OS boot to save time and
space. The cache is based off the checksum of the image we are about to
prepare. On the ubuntu side, the checksum is directly provided, so we
simply download the checksum and attempt to pull the cache. On the
windows side, no checksum is provided, so we must still download the
image and checksum it manually. This still saves time from needing to
actually prepare the images.

This saves space because we change the artifact uploading to only be
valid for a single day. However, the cached artifact is valid for
however long caches are valid for (I think 90 days?). This means that we
cache the prepared images once and can re-distribute it.

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

Ran the workflow once to cache the prepared images. Ran a second time to
make sure the cached images are properly retrieved.

## Integration Instructions

N/A

diff --git a/.github/workflows/prepare-images.yml b/.github/workflows/prepare-images.yml
--- a/.github/workflows/prepare-images.yml
+++ b/.github/workflows/prepare-images.yml
@@ -1,5 +1,11 @@
 # A reusable workflow to prepare OS boot images for Linux and Windows
 #
+# This action first checks the cache for an existing prepared image based on the checksum of the
+# base image. If not found, it downloads the base image, prepares it for OS boot testing, and
+# uploads the prepared image as an artifact for use in subsequent jobs. The retention date for the
+# published artifact is set to 1 day, as the actual storing of the prepared image is handled by the
+# cache.
+#
 ##
 # Copyright (c) Microsoft Corporation.
 #
@@ -33,16 +39,39 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Download image checksum
+        id: checksum
+        run: |
+          img_url=${{ inputs.image-url }}
+          img_name=$(basename "${img_url}")
+          checksum_url="${img_url%/*}/SHA256SUMS"
+
+          img_sha=$(curl -fsSL "${checksum_url}" | awk -v f="*${img_name}" '$2==f {print $1}')
+
+          [ -n "${img_sha}" ] || (echo "Failed to retrieve image checksum" >&2; exit 1)
+
+          echo "sha=${img_sha}" >> $GITHUB_OUTPUT
+      
+      - name: Cache Ubuntu cloud image
+        id: cache
+        uses: actions/cache@v4
+        with:
+          path: artifacts
+          key: ${{ inputs.artifact-name }}-${{ steps.checksum.outputs.sha }}
+
       - name: Install Dependencies
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           sudo apt update
           sudo apt install -y qemu-system-x86 qemu-system-aarch64 qemu-utils ovmf curl cloud-image-utils
       
       - name: Download Ubuntu IMG
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           curl -L "${{ inputs.image-url }}" -o "${{ env.IMG }}"
 
       - name: Create QCOW2 Image
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           # Create the differential qcow2
           qemu-img create -f qcow2 -b "${{ env.IMG }}" -F qcow2 "${{ env.DISK_IMAGE }}"
@@ -54,6 +83,7 @@ jobs:
           mv "${{ env.DISK_IMAGE }}-flat.qcow2" "${{ env.DISK_IMAGE }}"
                 
       - name: Make seed.iso
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           mkdir seed
           echo "instance-id: ci-vm-$(date +%s)" > seed/meta-data
@@ -64,16 +94,25 @@ jobs:
           echo "  condition: True" >> seed/user-data
 
       - name: Build seed ISO (cloud-init)
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           cloud-localds "${{ env.SEED_ISO }}" seed/user-data seed/meta-data
+      
+      - name: Move to artifacts directory
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          mkdir artifacts
+          mv "${{ env.DISK_IMAGE }}" artifacts/
+          mv "${{ env.SEED_ISO }}" artifacts/
       
       - name: Publish Artifacts
         uses: actions/upload-artifact@v6
         with:
           name: ${{ inputs.artifact-name }}
+          retention-days: 1
           path: |
-            ${{ env.DISK_IMAGE }}
-            ${{ env.SEED_ISO }}
+            artifacts/${{ env.DISK_IMAGE }}
+            artifacts/${{ env.SEED_ISO }}
             
   build-windows-images:
     name: Prepare Windows Boot Image
@@ -87,17 +126,37 @@ jobs:
       ARCHITECTURE: ${{ contains(inputs.artifact-name, 'aarch64') && 'arm64' || 'x64' }}
 
     steps:
+      - name: Download Windows Validation OS image and checksum'
+        id: checksum
+        run: |
+          Invoke-WebRequest -Uri "${{ inputs.image-url }}" -OutFile "${{ env.IMG }}"
+
+          $hash = (Get-FileHash -Path "${{ env.IMG }}" -Algorithm SHA256).Hash
+          Write-Host "Downloaded image SHA256: $hash" 
+
+          Add-Content -Path $env:GITHUB_OUTPUT -Value "sha=$hash"
+      
+      - name: Cache Windows cloud image
+        id: cache
+        uses: actions/cache@v4
+        with:
+          path: artifacts
+          key: ${{ inputs.artifact-name }}-${{ steps.checksum.outputs.sha }}
+
       - name: Install Dependencies
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           choco install -y qemu
           Install-Module -Name PS2EXE -Scope CurrentUser -Force
   
       - name: Setup .NET
+        if: steps.cache.outputs.cache-hit != 'true'
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: 6.0.x # 6.0.0 is specifically required for the WVOS Image Builder CLI.
 
       - name: Prepare Shutdown EXE
+        if: steps.cache.outputs.cache-hit != 'true'
         id: shutdown-exe
         run: |
           $script = 'Stop-Computer -Force'
@@ -108,12 +167,9 @@ jobs:
 
           Invoke-PS2EXE $scriptPath $exePath -noConsole -icon "$null"
           Write-Host "Shutdown EXE created at $env:GITHUB_WORKSPACE\$exePath"
-
-      - name: Download Windows Validation OS image
-        run: |
-          Invoke-WebRequest -Uri "${{ inputs.image-url }}" -OutFile "${{ env.IMG }}"
       
       - name: Mount Image and run OS Builder
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           $mountResult = Mount-DiskImage -ImagePath (Get-Item $env:IMG).FullName -PassThru
           $driveLetter = ($mountResult | Get-Volume).DriveLetter
@@ -127,6 +183,7 @@ jobs:
           & $cliPath -g -if vhdx -bt InternalDisk -sc "$exePath" -f powershell -f provisioning -o $env:GITHUB_WORKSPACE
       
       - name: Convert to qcow2
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           $vhdxPath = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter *.vhdx -Recurse -File | Select-Object -First 1
           Write-Host "Converting VHDX at $($vhdxPath.FullName) to QCOW2"
@@ -134,9 +191,16 @@ jobs:
           & "C:\Program Files\qemu\qemu-img.exe" convert -O qcow2 $($vhdxPath.FullName) "$env:GITHUB_WORKSPACE\${{ env.DISK_IMAGE }}"
           Write-Host "QCOW2 image created at $env:GITHUB_WORKSPACE\${{ env.DISK_IMAGE }}"
       
+      - name: Move to artifacts directory
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          mkdir artifacts
+          mv "${{ env.DISK_IMAGE }}" artifacts/
+      
       - name: Publish Artifacts
         uses: actions/upload-artifact@v6
         with:
           name: ${{ inputs.artifact-name }}
+          retention-days: 1
           path: |
-            ${{ env.DISK_IMAGE }}
+            artifacts/${{ env.DISK_IMAGE }}
